language: csharp
solution: travis-mono-test.sln

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir build && cd build && dotnet new && time dotnet restore && dotnet run; fi
